# SPDX-License-Identifier: GPL-3.0-or-later
function(cooperative_fixture_flags target)
    target_compile_features(${target} PRIVATE cxx_std_20)
    if(MSVC)
        target_compile_options(${target} PRIVATE /W4 /permissive- /bigobj /fp:strict)
        target_compile_definitions(${target} PRIVATE _CRT_SECURE_NO_WARNINGS NOMINMAX)
    elseif(CMAKE_CXX_COMPILER_ID MATCHES "^(GNU|Clang|AppleClang)$")
        target_compile_options(${target} PRIVATE -Wall -Wextra -msse4.1
            -fno-fast-math -frounding-math -ffp-contract=off)
    else()
        message(FATAL_ERROR "The fixture FP contract is defined for MSVC/GNU/Clang only")
    endif()
endfunction()

function(cooperative_require_runtime)
    if(NOT EXISTS "${PS2RECOMP_DIR}/ps2xRuntime/include/ps2_runtime.h")
        message(FATAL_ERROR "Set PS2RECOMP_DIR to the full patched source checkout")
    endif()
    if(NOT TARGET ps2_runtime)
        set(PS2X_BUILD_RECOMP OFF CACHE BOOL "" FORCE)
        set(PS2X_BUILD_RUNTIME ON CACHE BOOL "" FORCE)
        set(PS2X_BUILD_ANALYZER OFF CACHE BOOL "" FORCE)
        set(PS2X_BUILD_TEST OFF CACHE BOOL "" FORCE)
        set(PS2X_BUILD_STUDIO OFF CACHE BOOL "" FORCE)
        set(PS2X_ENABLE_DEBUG_UI OFF CACHE BOOL "" FORCE)
        set(PS2X_ENABLE_FFMPEG ON CACHE BOOL "" FORCE)
        add_subdirectory("${PS2RECOMP_DIR}" "${CMAKE_CURRENT_BINARY_DIR}/actual-runtime" EXCLUDE_FROM_ALL)
    endif()
    if(NOT TARGET ps2_runtime OR NOT TARGET ps2_iop)
        message(FATAL_ERROR "The actual runtime dependency graph is required")
    endif()
endfunction()

function(cooperative_runtime_fixture target fixture)
    add_executable(${target} "${fixture}" "${PS2RECOMP_DIR}/ps2xTest/src/test_function_table.cpp")
    cooperative_fixture_flags(${target})
    target_include_directories(${target} PRIVATE "${PS2RECOMP_DIR}/ps2xRuntime/include"
        "${PS2RECOMP_DIR}/ps2xIOP/include")
    target_link_libraries(${target} PRIVATE ps2_runtime)
    if(MSVC)
        target_link_options(${target} PRIVATE /STACK:16777216)
    endif()
    if(COMMAND ps2x_stage_ffmpeg_runtime_dlls)
        ps2x_stage_ffmpeg_runtime_dlls(${target})
    endif()
endfunction()
